### ISSUE TITLE
[EPIC] Ledger review requirements

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-ledger-app#13]
# Ledger requirements

Requirements to send the app for approval by the ledger team

## 16/08 - 20/08

- [x] Make a video showcasing the mais app features
    - Video must show verify public address, display sign tx info, reject and accept tx.
- [x] Validate that the icons follow the guidelines
- [x] Produce an Adobe Illustrator Template for the icons
- [x] Create a self-hosted public tutorial (support documentation) for the user on how to operate the wallet with ledger.}
    - [x] #16 
    - [x] #18 
- [ ] hathor support contact info

#### Aditional tasks

- [ ] remove path from display (improve user friendliness) : #17 
- [x] remove option to reject show address: #19 
- [ ] https://github.com/HathorNetwork/hathor-wallet/issues/216

## 23/08 - 27/08

- [x] hathor support contact info
- [x] remove path from display (improve user friendliness) : #17 
- [x] https://github.com/HathorNetwork/hathor-wallet/issues/216
