### ISSUE TITLE
[EPIC] Ledger Q3 [02/08/21]

### ISSUE THREAD

**Issue by r4mmer** [HathorNetwork/hathor-ledger-app#2]
# Ledger App

# July 14 - July 16

## Tasks
- [x] #11
- [x] **Document development docs, environment and tooling required**

# July 19 - July 23

## Tasks
- [x] #12
- [PARTIAL] #13
- [PARTIAL] #14
- [PARTIAL] #15
- [PARTIAL] #16
- [FAIL] **Unit and Integration tests**

### Features
:heavy_check_mark: ledger app works with `nano S` firmware v2.0.0
:heavy_check_mark: ledger can hold HTR tokens

# July 26 - July 30

## Tasks
- [x] #13
- [x] #14
- [x] #15
- [x] #16
- [FAIL] **Unit and Integration tests**
- [x] **Implement new ledger communication lib and tests**
- [x] **Implement ledger on wallet desktop**
- [x] #19

### Features
:heavy_check_mark: Wallet Desktop can manage ledger hathor app
:hourglass_flowing_sand: App compatible with nano S and nano X

# 02/08 - 06/08

## Tasks
- [PARTIAL] #3
    - [x] Wallet-lib PR
    - [x] Wallet desktop PR
        - :hourglass_flowing_sand:  waiting hathor-wallet-lib release
    - [x] #1
- [DONE] #5 PR: #6 // in review
- [DONE] #4 PR: #7 // in review
- [x] Linter: #8
- [DONE] Limits on bip32 paths: #10 // in review 
- [x] refactor: #9 

# 09/08 - 13/08

- [review] Limits on bip32 paths: #10 
- [x] #5 PR: #6
- [x] #4 PR: #7
- [x] Wallet desktop PR

# 16/08 - 20/08

- [x] Limits on bip32 paths: #10
